-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: patches/abstractSchemaChanges/patch-wikilove_log-cleanup.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/wikilove_log
CHANGE  wll_timestamp wll_timestamp BINARY(14) NOT NULL,
CHANGE  wll_sender_registration wll_sender_registration BINARY(14) DEFAULT NULL,
CHANGE  wll_receiver_registration wll_receiver_registration BINARY(14) DEFAULT NULL,
CHANGE  wll_receiver_editcount wll_receiver_editcount INT DEFAULT NULL,
CHANGE  wll_email wll_email TINYINT(1) DEFAULT 0 NOT NULL;