-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilove_log (
  wll_id INT AUTO_INCREMENT NOT NULL,
  wll_timestamp BINARY(14) NOT NULL,
  wll_sender INT UNSIGNED NOT NULL,
  wll_sender_registration BINARY(14) DEFAULT NULL,
  wll_sender_editcount INT DEFAULT NULL,
  wll_receiver INT UNSIGNED NOT NULL,
  wll_receiver_registration BINARY(14) DEFAULT NULL,
  wll_receiver_editcount INT DEFAULT NULL,
  wll_type VARCHAR(64) NOT NULL,
  wll_subject VARCHAR(255) NOT NULL,
  wll_message BLOB NOT NULL,
  wll_email TINYINT(1) DEFAULT 0 NOT NULL,
  INDEX wll_timestamp (wll_timestamp),
  INDEX wll_type_time (wll_type, wll_timestamp),
  INDEX wll_sender_time (wll_sender, wll_timestamp),
  INDEX wll_receiver_time (wll_receiver, wll_timestamp),
  PRIMARY KEY(wll_id)
) /*$wgDBTableOptions*/;
