-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: patches/abstractSchemaChanges/patch-wikilove_log-cleanup.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX wll_timestamp;
DROP  INDEX wll_type_time;
DROP  INDEX wll_sender_time;
DROP  INDEX wll_receiver_time;
CREATE TEMPORARY TABLE /*_*/__temp__wikilove_log AS
SELECT  wll_id,  wll_timestamp,  wll_sender,  wll_sender_registration,  wll_sender_editcount,  wll_receiver,  wll_receiver_registration,  wll_receiver_editcount,  wll_type,  wll_subject,  wll_message,  wll_email
FROM  /*_*/wikilove_log;
DROP  TABLE  /*_*/wikilove_log;
CREATE TABLE  /*_*/wikilove_log (    wll_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,    wll_timestamp BLOB NOT NULL,    wll_sender INTEGER UNSIGNED NOT NULL,    wll_sender_registration BLOB DEFAULT NULL,    wll_sender_editcount INTEGER DEFAULT NULL,    wll_receiver INTEGER UNSIGNED NOT NULL,    wll_receiver_registration BLOB DEFAULT NULL,    wll_receiver_editcount INTEGER DEFAULT NULL,    wll_type VARCHAR(64) NOT NULL,    wll_subject VARCHAR(255) NOT NULL,    wll_message BLOB NOT NULL,    wll_email SMALLINT DEFAULT 0 NOT NULL  );
INSERT INTO  /*_*/wikilove_log (    wll_id, wll_timestamp, wll_sender,    wll_sender_registration, wll_sender_editcount,    wll_receiver, wll_receiver_registration,    wll_receiver_editcount, wll_type,    wll_subject, wll_message, wll_email  )
SELECT  wll_id,  wll_timestamp,  wll_sender,  wll_sender_registration,  wll_sender_editcount,  wll_receiver,  wll_receiver_registration,  wll_receiver_editcount,  wll_type,  wll_subject,  wll_message,  wll_email
FROM  /*_*/__temp__wikilove_log;
DROP  TABLE /*_*/__temp__wikilove_log;
CREATE INDEX wll_timestamp ON  /*_*/wikilove_log (wll_timestamp);
CREATE INDEX wll_type_time ON  /*_*/wikilove_log (wll_type, wll_timestamp);
CREATE INDEX wll_sender_time ON  /*_*/wikilove_log (wll_sender, wll_timestamp);
CREATE INDEX wll_receiver_time ON  /*_*/wikilove_log (wll_receiver, wll_timestamp);