-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: patches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wikilove_log (
  wll_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wll_timestamp BLOB NOT NULL,
  wll_sender INTEGER UNSIGNED NOT NULL,
  wll_sender_registration BLOB DEFAULT NULL,
  wll_sender_editcount INTEGER DEFAULT NULL,
  wll_receiver INTEGER UNSIGNED NOT NULL,
  wll_receiver_registration BLOB DEFAULT NULL,
  wll_receiver_editcount INTEGER DEFAULT NULL,
  wll_type VARCHAR(64) NOT NULL,
  wll_subject VARCHAR(255) NOT NULL,
  wll_message BLOB NOT NULL,
  wll_email SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX wll_timestamp ON /*_*/wikilove_log (wll_timestamp);

CREATE INDEX wll_type_time ON /*_*/wikilove_log (wll_type, wll_timestamp);

CREATE INDEX wll_sender_time ON /*_*/wikilove_log (wll_sender, wll_timestamp);

CREATE INDEX wll_receiver_time ON /*_*/wikilove_log (wll_receiver, wll_timestamp);
