-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: patches/abstractSchemaChanges/patch-wikilove_log-cleanup.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  wikilove_log ALTER wll_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE  wikilove_log ALTER wll_timestamp
DROP  DEFAULT;
ALTER TABLE  wikilove_log ALTER wll_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE  wikilove_log ALTER wll_sender_registration TYPE TIMESTAMPTZ;
ALTER TABLE  wikilove_log ALTER wll_sender_registration
DROP  DEFAULT;
ALTER TABLE  wikilove_log ALTER wll_sender_registration TYPE TIMESTAMPTZ;
ALTER TABLE  wikilove_log ALTER wll_receiver_registration TYPE TIMESTAMPTZ;
ALTER TABLE  wikilove_log ALTER wll_receiver_registration
DROP  DEFAULT;
ALTER TABLE  wikilove_log ALTER wll_receiver_editcount
DROP  NOT NULL;
ALTER TABLE  wikilove_log ALTER wll_email TYPE SMALLINT;
ALTER TABLE  wikilove_log ALTER wll_email
SET  DEFAULT 0;