-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wikilove_log (
  wll_id SERIAL NOT NULL,
  wll_timestamp TEXT NOT NULL,
  wll_sender INT NOT NULL,
  wll_sender_registration TEXT DEFAULT NULL,
  wll_sender_editcount INT DEFAULT NULL,
  wll_receiver INT NOT NULL,
  wll_receiver_registration INT DEFAULT NULL,
  wll_receiver_editcount INT NOT NULL,
  wll_type VARCHAR(64) NOT NULL,
  wll_subject VARCHAR(255) NOT NULL,
  wll_message TEXT NOT NULL,
  wll_email INT DEFAULT 0 NOT NULL,
  PRIMARY KEY(wll_id)
);

CREATE INDEX wll_timestamp ON wikilove_log (wll_timestamp);

CREATE INDEX wll_type_time ON wikilove_log (wll_type, wll_timestamp);

CREATE INDEX wll_sender_time ON wikilove_log (wll_sender, wll_timestamp);

CREATE INDEX wll_receiver_time ON wikilove_log (wll_receiver, wll_timestamp);
